### ISSUE TITLE
codec truncates byte width

### ISSUE THREAD

**Issue by dt665m** [shawntabrizi/substrate-feeless-token-factory#6]
Hi @shawntabrizi, thanks for the blog post about this hackathon.  I understand that this is probably here more for posterity but there is a bug in this module that might be worth fixing.  

This only occurs in the unit tests because the mockup AccountId is set to u64.  Basically the MODULE_ID.into_sub_account() will generate the same account no matter the TokenId because into_sub_account uses the tuple ([u; 4], [u; 8, u32) to encode, but parity scale codec will try to decode that into back into u64 AccountId, causing extra bytes to be truncated.  

For the unit test to work "correctly", AccountId would need to be set to u128.  There aren't any tests that try multiple TokenIds so this is probably why it was missed.  A real runtime using the default sr25519 wont have this issue, however.

**Comment by shawntabrizi** [comment]
@dt665m cool catch!

Fixed it here while moving all the folders out: https://github.com/shawntabrizi/substrate-feeless-token-factory/commit/1c9e5b53de5b0a7caae6de191a68f6b0f5bfe818
